<a href="https://colab.research.google.com/github/javiermingo/hello-world/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

!wget https://raw.githubusercontent.com/Exploratorio-DCC-PUC/Syllabus/master/Tareas/Tarea%20Grande%201/movies.csv
datos = pd.read_csv("movies.csv", encoding="latin-1")
datos

--2020-04-03 15:19:59--  https://raw.githubusercontent.com/Exploratorio-DCC-PUC/Syllabus/master/Tareas/Tarea%20Grande%201/movies.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 969276 (947K) [text/plain]
Saving to: ‘movies.csv.5’

movies.csv.5        100%[===================>] 946.56K  --.-KB/s    in 0.08s

2020-04-03 15:19:59 (11.2 MB/s) - ‘movies.csv.5’ saved [969276/969276]

          budget  ...  year
0      8000000.0  ...  1986
1      6000000.0  ...  1986
2     15000000.0  ...  1986
3     18500000.0  ...  1986
4      9000000.0  ...  1986
...          ...  ...   ...
6815         0.0  ...  2016
6816         0.0  ...  2016
6817   3500000.0  ...  2016
6818         0.0  ...  2016
6819         0.0  ...  2016

[6820 rows x 15 columns]

In [0]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6820 entries, 0 to 6819
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   budget    6820 non-null   float64
 1   company   6820 non-null   object
 2   country   6820 non-null   object
 3   director  6820 non-null   object
 4   genre     6820 non-null   object
 5   gross     6820 non-null   float64
 6   name      6820 non-null   object
 7   rating    6820 non-null   object
 8   released  6820 non-null   object
 9   runtime   6820 non-null   int64
 10  score     6820 non-null   float64
 11  star      6820 non-null   object
 12  votes     6820 non-null   int64
 13  writer    6820 non-null   object
 14  year      6820 non-null   int64
dtypes: float64(3), int64(3), object(9)
memory usage: 799.3+ KB

In [0]:
nuevo = pd.DataFrame(datos)
nuevo.describe()

             budget         gross  ...         votes         year
count  6.820000e+03  6.820000e+03  ...  6.820000e+03  6820.000000
mean   2.458113e+07  3.349783e+07  ...  7.121952e+04  2001.000293
std    3.702254e+07  5.819760e+07  ...  1.305176e+05     8.944501
min    0.000000e+00  7.000000e+01  ...  2.700000e+01  1986.000000
25%    0.000000e+00  1.515839e+06  ...  7.665250e+03  1993.000000
50%    1.100000e+07  1.213568e+07  ...  2.589250e+04  2001.000000
75%    3.200000e+07  4.006534e+07  ...  7.581225e+04  2009.000000
max    3.000000e+08  9.366622e+08  ...  1.861666e+06  2016.000000

[8 rows x 6 columns]

In [0]:
nuevo['score'] = nuevo.score.round()
a = nuevo["score"]
a

0       8.0
1       8.0
2       7.0
3       8.0
4       7.0
       ...
6815    5.0
6816    5.0
6817    6.0
6818    6.0
6819    7.0
Name: score, Length: 6820, dtype: float64

In [0]:
a

0       8.0
1       8.0
2       7.0
3       8.0
4       7.0
       ...
6815    5.0
6816    5.0
6817    6.0
6818    6.0
6819    7.0
Name: score, Length: 6820, dtype: float64

In [0]:
a.value_counts()

6.0    2588
7.0    2186
8.0     908
5.0     810
4.0     246
3.0      38
9.0      24
2.0      20
Name: score, dtype: int64

In [0]:
import altair as alt

source = pd.DataFrame({
    'nota': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', "_10" ],
    'frecuencia': [0, 0, 20, 38, 246, 810, 2588, 2186, 908, 24, 0]
})

alt.Chart(source).mark_bar().encode(
    x='nota',
    y='frecuencia'
)

alt.Chart(...)

In [0]:
nuevo1 = pd.DataFrame(datos)
b = nuevo1["score"]
b

0       8.1
1       7.8
2       6.9
3       8.4
4       6.9
       ...
6815    5.4
6816    4.9
6817    6.5
6818    6.2
6819    6.7
Name: score, Length: 6820, dtype: float64

In [0]:
c = nuevo1.nlargest(10, 'score')
c

           budget                    company  ...             writer  year
1760   25000000.0  Castle Rock Entertainment  ...       Stephen King  1994
4840  185000000.0               Warner Bros.  ...     Jonathan Nolan  2008
1542   22000000.0         Universal Pictures  ...    Thomas Keneally  1993
1761    8000000.0                    Miramax  ...  Quentin Tarantino  1994
3743   94000000.0            New Line Cinema  ...     J.R.R. Tolkien  2003
1762   55000000.0         Paramount Pictures  ...      Winston Groom  1994
2860   63000000.0          Fox 2000 Pictures  ...    Chuck Palahniuk  1999
3301   93000000.0            New Line Cinema  ...     J.R.R. Tolkien  2001
5280  160000000.0               Warner Bros.  ...  Christopher Nolan  2010
881    25000000.0               Warner Bros.  ...   Nicholas Pileggi  1990

[10 rows x 15 columns]

In [0]:
source = data.c()

alt.Chart(source).mark_bar().encode(
    x='name',
    y="score",
    # The highlight will be set on the result of a conditional statement
    color=alt.condition(
        alt.datum.year == 1810,  # If the year is 1810 this test returns True,
        alt.value('orange'),     # which sets the bar orange.
        alt.value('steelblue')   # And if it's not true it sets the bar steelblue.
    )
).properties(width=600)

alt.Chart(...)

           budget                    company  ...             writer  year
1760   25000000.0  Castle Rock Entertainment  ...       Stephen King  1994
4840  185000000.0               Warner Bros.  ...     Jonathan Nolan  2008
1542   22000000.0         Universal Pictures  ...    Thomas Keneally  1993
1761    8000000.0                    Miramax  ...  Quentin Tarantino  1994
3743   94000000.0            New Line Cinema  ...     J.R.R. Tolkien  2003
1762   55000000.0         Paramount Pictures  ...      Winston Groom  1994
2860   63000000.0          Fox 2000 Pictures  ...    Chuck Palahniuk  1999
3301   93000000.0            New Line Cinema  ...     J.R.R. Tolkien  2001
5280  160000000.0               Warner Bros.  ...  Christopher Nolan  2010
881    25000000.0               Warner Bros.  ...   Nicholas Pileggi  1990

[10 rows x 15 columns]

In [120]:
hola = pd.DataFrame(c)

alt.Chart(hola).mark_bar().encode(
    x=alt.X('name', sort="-y"),
    y=alt.Y("score"),
    # The highlight will be set on the result of a conditional statement
    color=alt.condition(
        alt.datum.name == "The Shawshank Redemption",  # If the year is 1810 this test returns True,
        alt.value('orange'),     # which sets the bar orange.
        alt.value('steelblue')   # And if it's not true it sets the bar steelblue.
    )
).properties(width=600)

alt.Chart(...)